-- Q 1 which chanal most frequently used for transactions?

select
TOP 1 * FROM 
		(SELECT store_type,
		count (transaction_id) as [Total Frequency]
		from tbl_transaction
		group by store_type) AS T1
		order by [Total Frequency] desc

--**************************************************************************************************************
-- Q 2 COUNT OF MALE AND FEMALE CUSTOMERS

SELECT 
GENDER,
COUNT (GENDER) [TOTAL NO.] FROM TBL_Customer
WHERE  GENDER  IN ('M','F')
GROUP BY Gender

--***************************************************************************************************************

-- Q 3 WHICH CITY WE HAVE MAXIMUM NO. OF CUSTOMER AND HOW MANY?

SELECT TOP 1 * FROM
					(SELECT CITY_CODE,
					 COUNT (CUSTOMER_ID) AS CUSTOMERS
					 FROM TBL_Customer
					 GROUP BY city_code) AS T2
                     ORDER BY CUSTOMERS DESC

--*****************************************************************************************************************
--Q 4 HOW MANY SUB CATEGORY ARE THERE UNDER BOOK CATEGORY?

SELECT
prod_cat_code ,prod_cat, 
count (prod_subcat) as [ Total SubCategory]
FROM TBL_Prodinfo
where prod_cat = 'Books'
group by prod_cat, prod_cat_code

--*****************************************************************************************************************
-- Q 5 Maximum quantity of product ever order.
select 
max (qty) as [Maximum quantity]
from TBL_Transaction

--******************************************************************************************************************
-- Q 6 Net total revenue generated in category  Electronics and books?
select 
prod_cat as [Product cetegoty],
SUM (total_amt) as Revenue  
from TBL_Transaction left join TBL_ProdInfo on TBL_Transaction.prod_cat_code = TBL_ProdInfo.prod_cat_code
and TBL_Transaction.prod_subcat_code = TBL_ProdInfo.prod_sub_cat_code
where prod_cat in ('Electronics','books')
group by prod_cat

--***********************************************************************************************************************
-- Q 7 how many cutomers have  > 10 trasaction excluding returns?

select
cust_id,
COUNT(transaction_id) as [Total Transactions]
from TBL_Transaction
where Rate >0 
group by cust_id
having COUNT(transaction_id) >10 

--************************************************************************************************************************

-- Q 8 what is total revenue earned by electronics , clothing category from flagship store?

select 
store_type,prod_cat as [Product cetegoty], 
SUM (total_amt) Revenue
from TBL_Transaction left join TBL_ProdInfo on TBL_Transaction.prod_cat_code = TBL_ProdInfo.prod_cat_code
and TBL_Transaction.prod_subcat_code = TBL_ProdInfo.prod_sub_cat_code
where prod_cat in ('Electronics','clothing') and Store_type = 'flagship store'

group by store_type, prod_cat

--*************************************************************************************************************************

-- Q 9 whate is total revenue generated by Male customer in electronic category?

select 
prod_subcat as [Product sub cetegoty], 
SUM (total_amt) [Total Revenue]
from TBL_Transaction left join TBL_ProdInfo on TBL_Transaction.prod_cat_code = TBL_ProdInfo.prod_cat_code
and TBL_Transaction.prod_subcat_code = TBL_ProdInfo.prod_sub_cat_code
left join TBL_Customer on customer_Id = cust_id
where prod_cat = 'Electronics' and Gender = 'M'
group by prod_subcat

--**************************************************************************************************************************
-- Q 10 whate is the percentage of sales and return and display top 5

SELECT 
TOP 5 T1.prod_subcat,
totalReturn1 * 100 / totalSALE AS [Percentage Return]
FROM
(select 
Prod_subcat,
sum (abs(total_amt )) as totalReturn1 
from TBL_Transaction left join TBL_ProdInfo on TBL_Transaction.prod_cat_code = TBL_ProdInfo.prod_cat_code
and TBL_Transaction.prod_subcat_code = TBL_ProdInfo.prod_sub_cat_code 
where rate<0 
group by prod_subcat) AS T1
LEFT JOIN
(select prod_subcat,
sum (total_amt ) totalSALE
from TBL_Transaction left join TBL_ProdInfo on TBL_Transaction.prod_cat_code = TBL_ProdInfo.prod_cat_code
and TBL_Transaction.prod_subcat_code = TBL_ProdInfo.prod_sub_cat_code
group by prod_subcat
) AS T2 
 ON T1.pROD_SUBCAT = T2.PROD_SUBCAT
 ORDER BY totalSALE DESC